// pages/characters/[characterName]/movies.tsx
import { useEffect, useState } from 'react';
import { useRouter } from 'next/router';
import { useCharacters } from '../../../context/characters';
import type { MoviesResponse, PeopleResponse } from '../../../types';
import { GetStaticPaths, GetStaticProps } from 'next';

export const getStaticPaths: GetStaticPaths = async () => {
  const response = await fetch('https://swapi.dev/api/people?page=1');
  const data: PeopleResponse = await response.json();
  const paths = data.results.map((c) => ({
    params: { characterName: c.name },
  }));
  return {
    paths,
    fallback: false,
  };
};

export const getStaticProps: GetStaticProps = async (_context) => {
  return {
    props: {},
  };
};

export default function CharacterMovies(): React.ReactElement {
  const router = useRouter();
  const { characterName } = router.query;
  const { characters, fetchCharacters } = useCharacters();
  const currentCharacter =
    characters?.find(
      (c) => c.name === decodeURIComponent(characterName as string)
    ) ?? null;

  const [data, setData] = useState<MoviesResponse | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [isError, setIsError] = useState(false);

  useEffect(() => {
    if (currentCharacter === null) {
      fetchCharacters();
    }
  }, [currentCharacter, fetchCharacters]);

  useEffect(() => {
    if (data === null && !isLoading && !isError && currentCharacter) {
      setIsLoading(true);
      fetch('https://swapi.dev/api/films')
        .then((res) => {
          if (res.ok) {
            return res.json();
          } else {
            throw new Error('Star Wars films request failed');
          }
        })
        .then((swapiData) => {
          setData(swapiData);
          setIsLoading(false);
        })
        .catch((_error) => {
          setIsError(true);
          setIsLoading(false);
        });
    }
  }, [data, setData, isLoading, isError, currentCharacter, fetchCharacters]);

  let content: React.ReactElement;

  if (isError) {
    content = (
      <div role='alert'>
        There was a problem loading Star Wars characters, please try refreshing
        the page
      </div>
    );
  } else if (isLoading || data === null) {
    content = <div role='status'>Loading character&apos;s movies...</div>;
  } else {
    content = (
      <ul>
        {data.results
          .filter((m) => currentCharacter?.films.includes(m.url))
          .map((movie) => (
            <li key={movie.title}>{movie.title}</li>
          ))}
      </ul>
    );
  }

  return (
    <section aria-labelledby='character-movies-heading'>
      <h2 id='character-movies-heading'>
        {decodeURIComponent(characterName as string)} Movies
      </h2>
      {content}
    </section>
  );
}

// src/routes/characters/[name]/movies.svelte
<script lang="ts" context="module">
  import type { Load } from '@sveltejs/kit';

  export const load: Load = async ({ page }) => {
    return {
      props: {
        characterName: decodeURIComponent(page.params.name),
      },
    };
  };
</script>

<script lang="ts">
  import { movies } from '../../../stores/movies';
  import { characters, fetchCharacters } from '../../../stores/characters';
  import { onMount } from 'svelte';
  import type { Movie, MoviesResponse } from '../../../types';

  export let characterName: string;

  let movieData: Movie[] | undefined;
  let isError = false;
  let isLoading = false;

  $: character = $characters?.find((c) => c.name === characterName);
  $: characterMovies = movieData?.filter((m) => character?.films.includes(m.url));

  onMount(async () => {
    if ($movies === undefined) {
      isLoading = true;
      try {
        const response = await fetch('https://swapi.dev/api/films');
        movieData = ((await response.json()) as MoviesResponse).results;
        movies.set(movieData);
        isLoading = false;
      } catch {
        isError = true;
        isLoading = false;
      }
    } else {
      movieData = $movies;
    } 
    if (character === undefined) {
      fetchCharacters();
    }
  });
</script>

<section aria-labelledby="character-movies-heading">
  <h2 id="character-movies-heading">{characterName} Movies</h2>
  {#if isError}
    <div role="alert">
      There was a problem loading {characterName}'s movies, please try refreshing the page
    </div>
  {:else if isLoading || characterMovies === undefined}
    <div role="status">Loading character's movies...</div>
  {:else}
    <ul>
      {#each characterMovies as movie}
        <li>
          {movie.title}
        </li>
      {/each}
    </ul>
  {/if}
</section>
