// src/Characters.tsx
import { useEffect, useState } from 'react';

interface Character {
  name: string;
}

interface PeopleResponse {
  results: Character[];
}

function Characters(): React.ReactElement {
  const [data, setData] = useState<PeopleResponse | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [isError, setIsError] = useState(false);

  useEffect(() => {
    if (data === null && !isLoading && !isError) {
      setIsLoading(true);
      fetch('https://swapi.dev/api/people?page=1')
        .then((res) => {
          if (res.ok) {
            return res.json();
          } else {
            throw new Error('Star Wars people request failed');
          }
        })
        .then((swapiData) => {
          setData(swapiData);
          setIsLoading(false);
        })
        .catch((_error) => {
          setIsError(true);
          setIsLoading(false);
        });
    }
  }, [data, setData, isLoading, isError]);

  let content: React.ReactElement;

  if (isError) {
    content = (
      <div role='alert'>
        There was a problem loading Star Wars characters, please try refreshing
        the page
      </div>
    );
  } else if (isLoading || data === null) {
    content = <div role='status'>Loading characters...</div>;
  } else {
    content = (
      <ul>
        {data.results.map((character) => (
          <li>{character.name}</li>
        ))}
      </ul>
    );
  }

  return (
    <section aria-labelledby='characters-heading'>
      <h2 id='characters-heading'>Characters</h2>
      {content}
    </section>
  );
}

export default Characters;

// src/components/characters.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { characters } from '../stores/characters';
  import type { PeopleResponse, Character } from '../types';

  let data: Character[] | undefined;
  let isError = false;
  let isLoading = false;

  onMount(async () => {
    if ($characters === undefined) {
      isLoading = true;
      try {
        const response = await fetch('https://swapi.dev/api/people?page=1');
        data = ((await response.json()) as PeopleResponse).results;
        characters.set(data);
        isLoading = false;
      } catch {
        isError = true;
        isLoading = false;
      }
    } else {
      data = $characters;
    }
  });
</script>

<section aria-labelledby="characters-heading">
  <h2 id="characters-heading">Characters</h2>
  {#if isError}
    <div role="alert">
      There was a problem loading Star Wars characters, please try refreshing the page
    </div>
  {:else if isLoading || data === undefined}
    <div role="status">Loading characters...</div>
  {:else}
    <ul>
      {#each data as character}
        <li>
          <a href={`/characters/${encodeURIComponent(character.name)}/movies`}>
            {character.name}
          </a>
        </li>
      {/each}
    </ul>
  {/if}
</section>
